# Generated by Django 4.1.3 on 2023-02-07 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Objavlenie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adress', models.CharField(max_length=50, verbose_name='Адрес')),
                ('price', models.TextField(verbose_name='Цена')),
                ('decribe', models.TextField(verbose_name='Описание')),
                ('count_room', models.TextField(verbose_name='Кол-во комнат')),
                ('type_hous', models.TextField(verbose_name='Тип дома')),
                ('img', models.ImageField(upload_to='', verbose_name='Фото')),
            ],
        ),
    ]
