# Generated by Django 4.1.3 on 2023-02-07 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_objavlenie'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='ФИО')),
                ('img', models.ImageField(upload_to='', verbose_name='Фотка')),
                ('age', models.TextField(verbose_name='Возраст')),
                ('major', models.TextField(verbose_name='Специальность')),
                ('staz', models.TextField(verbose_name='Стаж')),
                ('salary', models.TextField(verbose_name='ЗП')),
            ],
        ),
    ]
